# Generated by Django 5.0.1 on 2024-03-02 13:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClubTypes',
            new_name='ClubType',
        ),
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
        migrations.RenameModel(
            old_name='Responses',
            new_name='Response',
        ),
        migrations.RenameModel(
            old_name='Types',
            new_name='Type',
        ),
    ]
