# Generated by Django 5.0.1 on 2024-03-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_clubtypes_clubtype_rename_questions_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookclub',
            name='types',
            field=models.ManyToManyField(to='main.type'),
        ),
        migrations.DeleteModel(
            name='ClubType',
        ),
    ]
